/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('products').del();

  await knex('products').insert([
    {
      id: 1,
      name: 'Filtro de Óleo Bosch',
      description: 'Filtro de óleo para motores 1.0 a 2.0, garantindo máxima proteção e performance',
      category: 'filtros',
      subcategory: 'oleo',
      price: 35.90,
      sale_price: null,
      promo_price: 29.90,
      cost_price: 20.00,
      images: JSON.stringify(['/api/placeholder/300/300']),
      stock: 25,
      min_stock: 5,
      sku: 'BOSCH-FO-001',
      supplier: 'Bosch',
      is_active: true,
      rating: 4.5,
      rating_count: 12,
      specifications: JSON.stringify({ capacidade: '1L', tipo: 'sintético', compatibilidade: 'Universal' }),
      vehicle_compatibility: JSON.stringify(['VW Gol', 'Fiat Uno', 'Chevrolet Celta', 'Ford Ka']),
      views_count: 45,
      sales_count: 8,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 2,
      name: 'Pastilha de Freio Dianteira',
      description: 'Pastilha de freio para veículos populares com alta durabilidade e segurança',
      category: 'freios',
      subcategory: 'pastilhas',
      price: 89.90,
      sale_price: null,
      promo_price: null,
      cost_price: 50.00,
      images: JSON.stringify(['/api/placeholder/300/300']),
      stock: 15,
      min_stock: 3,
      sku: 'FERODO-PF-001',
      supplier: 'Ferodo',
      is_active: true,
      rating: 4.8,
      rating_count: 24,
      specifications: JSON.stringify({ material: 'cerâmica', vida_util: '50000km', posicao: 'dianteira' }),
      vehicle_compatibility: JSON.stringify(['VW Gol', 'Fiat Palio', 'Chevrolet Corsa']),
      views_count: 67,
      sales_count: 15,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 3,
      name: 'Óleo Motor Castrol 5W30',
      description: 'Óleo sintético premium para motores modernos, máxima proteção e economia',
      category: 'lubrificantes',
      subcategory: 'motor',
      price: 45.90,
      sale_price: 39.90,
      promo_price: null,
      cost_price: 25.00,
      images: JSON.stringify(['/api/placeholder/300/300']),
      stock: 50,
      min_stock: 10,
      sku: 'CASTROL-OM-001',
      supplier: 'Castrol',
      is_active: true,
      rating: 4.9,
      rating_count: 35,
      specifications: JSON.stringify({ viscosidade: '5W30', capacidade: '1L', tipo: 'sintético' }),
      vehicle_compatibility: JSON.stringify(['Todos os veículos']),
      views_count: 120,
      sales_count: 28,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 4,
      name: 'Bateria 60Ah Moura',
      description: 'Bateria automotiva 60Ah com 18 meses de garantia',
      category: 'eletrica',
      subcategory: 'baterias',
      price: 320.00,
      sale_price: null,
      promo_price: 289.90,
      cost_price: 200.00,
      images: JSON.stringify(['/api/placeholder/300/300']),
      stock: 8,
      min_stock: 2,
      sku: 'MOURA-BAT-60AH',
      supplier: 'Moura',
      is_active: true,
      rating: 4.6,
      rating_count: 18,
      specifications: JSON.stringify({ amperagem: '60Ah', voltagem: '12V', garantia: '18 meses' }),
      vehicle_compatibility: JSON.stringify(['VW Gol', 'Fiat Palio', 'Chevrolet Corsa', 'Ford Ka']),
      views_count: 89,
      sales_count: 5,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 5,
      name: 'Kit Embreagem Sachs',
      description: 'Kit completo de embreagem com disco, platô e rolamento',
      category: 'transmissao',
      subcategory: 'embreagem',
      price: 450.00,
      sale_price: 399.90,
      promo_price: null,
      cost_price: 280.00,
      images: JSON.stringify(['/api/placeholder/300/300']),
      stock: 6,
      min_stock: 2,
      sku: 'SACHS-KIT-EMB-001',
      supplier: 'Sachs',
      is_active: true,
      rating: 4.7,
      rating_count: 9,
      specifications: JSON.stringify({ itens: 'Disco + Platô + Rolamento', garantia: '12 meses' }),
      vehicle_compatibility: JSON.stringify(['VW Gol 1.0/1.6', 'Fiat Palio 1.0/1.4']),
      views_count: 34,
      sales_count: 3,
      created_at: new Date(),
      updated_at: new Date()
    }
  ]);
};
